### ISSUE TITLE
I have luacheck in PATH, not in .deps/usr/bin/

### ISSUE THREAD

**Issue by teto** [neovim/nvimdev.nvim#22]
When using non bundled dependencies, .deps/usr/bin/luacheck is not available 
`Exe (/home/teto/neovim/.deps/usr/bin/luacheck) of maker nvimluacheck is not executable`
but I have luacheck in PATH :s 
https://github.com/neovim/nvimdev.nvim/blob/2acfca2a9a55fd66a235cf2e6f602ba1d46add25/autoload/nvimdev.vim#L110
Ironically, the solution might be in the PR I am working on https://github.com/neovim/neovim/pull/7202 since we could just add s:path to PATH.

**Comment by blueyed** [comment]
Yeah, nvimdev should probably not mess with luacheck in the first place, other from maybe setting the path for the existing one via `.deps` in some way.

**Comment by blueyed** [comment]
See https://github.com/neovim/nvimdev.nvim/pull/24.
Should help with your issue already (without using the Neomake patch), since it will just use your regular luacheck then.
