### ISSUE TITLE
time to archive this?

### ISSUE THREAD

**Issue by justinmk** [neovim/nvimdev.nvim#34]
- This repo is not seeing much activity.
- LSP is well-supported by Nvim, and the clangd LS works well on the Nvim codebase.

## stuff worth preserving

- the projectionist model could be mentioned in `:help develop.txt` or maybe `src/nvim/README.md` https://github.com/neovim/nvimdev.nvim/blob/994ff5daf571ad02cc96436002411b4fb235c91f/autoload/nvimdev.vim#L10-L33

**Comment by clason** [comment]
In any case, https://github.com/folke/lua-dev.nvim should supersede this...

**Comment by lewis6991** [comment]
I'm looking at reviving this. I've already opened #35 which uses modern Nvim features to help running functional tests.
